version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - L2jLiga
    reviewers:
      - L2jLiga
    commit-message:
      prefix: "chore: "

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - L2jLiga
    reviewers:
      - L2jLiga
    commit-message:
      prefix: "chore: "
