version: 2
updates:
  # Library
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: "

  # Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: "

  # Examples
  - package-ecosystem: "npm"
    directory: "/examples/controllers"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: "

  - package-ecosystem: "npm"
    directory: "/examples/request-handlers"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: "

  - package-ecosystem: "npm"
    directory: "/examples/swagger"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: "

  - package-ecosystem: "npm"
    directory: "/examples/typeorm"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: "
