version: 2
updates:
  # Library
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - L2jLiga
    reviewers:
      - L2jLiga
    commit-message:
      prefix: "chore: "

  # Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - L2jLiga
    reviewers:
      - L2jLiga
    commit-message:
      prefix: "chore: "

  # Examples
  - package-ecosystem: "npm"
    directory: "/examples"
    schedule:
      interval: "daily"
    assignees:
      - L2jLiga
    reviewers:
      - L2jLiga
    commit-message:
      prefix: "chore: "

  - package-ecosystem: "npm"
    directory: "/examples/typeorm"
    schedule:
      interval: "daily"
    assignees:
      - L2jLiga
    reviewers:
      - L2jLiga
    commit-message:
      prefix: "chore: "
