/**
 * @license
 * Copyright Andrey Chalkin <L2jLiga@gmail.com> (https://github.com/L2jLiga). All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/L2jLiga/fastify-decorators/blob/master/LICENSE
 */

import { _InjectablesHolder } from '../registry/_injectables-holder.js';
import type { ServiceMock } from './service-mock.js';

export class MocksManager {
  static create(injectables: _InjectablesHolder, mocks: ServiceMock[] = []): _InjectablesHolder {
    const mocksMap = new _InjectablesHolder();
    mocksMap.autoGenerated = new Map(injectables.entries());

    new Map().entries();

    for (const { provide, useValue } of mocks) {
      mocksMap.injectSingleton(provide, useValue);
    }

    return mocksMap;
  }
}
