import { _InjectablesHolder } from '../registry/_injectables-holder.js';
import type { ServiceMock } from './service-mock.js';

export class MocksManager {
  static create(injectables: _InjectablesHolder, mocks: ServiceMock[] = []): _InjectablesHolder {
    const mocksMap = new _InjectablesHolder();
    mocksMap.autoGenerated = new Map(injectables.entries());

    for (const { provide, useValue } of mocks) {
      mocksMap.injectSingleton(provide, useValue);
    }

    return mocksMap;
  }
}
