name: Linter

on:
  push:
    branches: [v*, next]
  pull_request:
    branches: [v*, next]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install --frozen-lock-file
      - name: Lint project
        run: yarn lint
