name: Build example

on:
  push:
    branches: [v*]
  pull_request:
    branches: [v*]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example: [controllers, error-handlers, request-handlers, swagger, typeorm, typescript-3.4]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install --frozen-lock-file
      - name: Build library
        run: yarn build:lib
      - name: Build "${{ matrix.example }}"
        run: |
          cd examples
          cd ${{ matrix.example }}
          yarn install
          yarn build
      - name: Run tests on example
        run: |
          cd examples
          cd ${{ matrix.example }}
          yarn test
        env:
          CI: true
      - name: Upload examples code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: coverage/examples
          flags: examples
